
name: Build and upload conda package

on:
  release:
    types: [released]

env:
  CONDA_SUBDIR: osx-arm64
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  conda_deployment:
    name: Conda deployment of package with ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
          auto-update-conda: false
          auto-activate-base: true
          show-channel-urls: true
      - name: Build and upload the conda packages
        run: |
          conda build devtools/conda-build --no-test --output-folder ./build -c conda-forge
          for filename in $dirname/*; do
            if [ "${filename: -8}" == ".tar.bz2" ]; then
              anaconda upload --user statphysbio --label $filename
            fi
          done